INFO: Starting training:
        Epochs:          1
        Batch size:      4
        Learning rate:   1e-05
        Training size:   759
        Validation size: 84
        Checkpoints:     True
        Device:          cpu
        Images scaling:  0.5
        Mixed Precision: False
Epoch 1/1:   0%|                                                                              | 0/759 [00:00<?, ?img/s]D:\Python37\lib\site-packages\torch\autocast_mode.py:162: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')

















Epoch 1/1:   9%|████▋                                             | 72/759 [04:58<47:42,  4.17s/img, loss (batch)=5.79]







































Epoch 1/1:  19%|█████████▎                                       | 144/759 [10:59<41:30,  4.05s/img, loss (batch)=5.34]


























Epoch 1/1:  22%|██████████▌                                      | 164/759 [13:47<50:02,  5.05s/img, loss (batch)=5.16]
Traceback (most recent call last):
  File "D:\Python37\lib\multiprocessing\queues.py", line 238, in _feed
    send_bytes(obj)
  File "D:\Python37\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "D:\Python37\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] 管道正在被关闭。
INFO: Saved interrupt